const express = require('express');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// In-memory store for settings and projects
let llmConfig = {
  baseUrl: process.env.MODEL_BASE_URL || 'https://api.openai.com/v1',
  apiKey: process.env.MODEL_API_KEY || '',
  modelName: 'gpt-4o'
};

let savedProjects = [];

// API Endpoints

// 1. LLM Model Settings
app.get('/api/config', (req, res) => {
  res.json({
    baseUrl: llmConfig.baseUrl,
    modelName: llmConfig.modelName,
    hasApiKey: Boolean(llmConfig.apiKey)
  });
});

app.post('/api/config', (req, res) => {
  const { baseUrl, apiKey, modelName } = req.body;
  if (baseUrl !== undefined) llmConfig.baseUrl = baseUrl;
  if (apiKey !== undefined) llmConfig.apiKey = apiKey;
  if (modelName !== undefined) llmConfig.modelName = modelName;

  res.json({
    success: true,
    message: 'Configuration updated successfully',
    config: {
      baseUrl: llmConfig.baseUrl,
      modelName: llmConfig.modelName,
      hasApiKey: Boolean(llmConfig.apiKey)
    }
  });
});

// 2. Luau AI Script Assistant (Lemonade & ForgeGUI inspired)
app.post('/api/generate-script', (req, res) => {
  const { prompt, scriptType } = req.body;
  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required' });
  }

  const type = scriptType || 'ServerScript';
  const timestamp = new Date().toISOString();

  // Template generators based on prompt keywords
  let generatedCode = '';
  let explanation = '';

  if (prompt.toLowerCase().includes('inventory')) {
    generatedCode = `-- Luau Inventory System (${type})
-- Generated by AI Game Studio
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local InventoryData = {}

local function setupInventory(player)
    InventoryData[player.UserId] = {
        Coins = 100,
        Items = {"Starter Sword", "Health Potion"}
    }
    print("Inventory initialized for " .. player.Name)
end

Players.PlayerAdded:Connect(setupInventory)
`;
    explanation = 'Generates a robust player inventory system template with item storage and player setup handlers.';
  } else if (prompt.toLowerCase().includes('leaderboard') || prompt.toLowerCase().includes('leaderstats')) {
    generatedCode = `-- Luau Leaderstats System (${type})
-- Generated by AI Game Studio
local Players = game:GetService("Players")

local function onPlayerAdded(player)
    local leaderstats = Instance.new("Folder")
    leaderstats.Name = "leaderstats"
    leaderstats.Parent = player

    local coins = Instance.new("IntValue")
    coins.Name = "Coins"
    coins.Value = 0
    coins.Parent = leaderstats

    local level = Instance.new("IntValue")
    level.Name = "Level"
    level.Value = 1
    level.Parent = leaderstats
end

Players.PlayerAdded:Connect(onPlayerAdded)
`;
    explanation = 'Creates standard Roblox leaderstats with Coins and Level trackers.';
  } else {
    generatedCode = `-- Luau Custom Feature Script (${type})
-- Prompt: ${prompt}
-- Generated at: ${timestamp}

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

print("Initializing AI Generated Module: ${prompt.replace(/\n/g, ' ')}")

local function executeFeature(player)
    -- Custom logic for: ${prompt}
    return true
end

return {
    Execute = executeFeature
}
`;
    explanation = `Generated custom Luau module for feature: "${prompt}".`;
  }

  res.json({
    success: true,
    prompt,
    scriptType: type,
    code: generatedCode,
    explanation,
    modelUsed: llmConfig.modelName
  });
});

// 3. Roblox GUI & UI Layout Generator (ForgeGUI & Nilo inspired)
app.post('/api/generate-gui', (req, res) => {
  const { prompt, theme } = req.body;
  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required' });
  }

  const selectedTheme = theme || 'Dark Gaming';

  const guiSpecs = {
    title: prompt,
    theme: selectedTheme,
    elements: [
      {
        type: 'Frame',
        name: 'MainPanel',
        size: { x: 400, y: 300 },
        position: { x: 0.5, y: 0.5 },
        backgroundColor: '#1e1e2e',
        borderColor: '#89b4fa',
        children: [
          {
            type: 'TextLabel',
            name: 'TitleHeader',
            text: prompt.toUpperCase(),
            textColor: '#cdd6f4',
            size: { x: 380, y: 40 },
            position: { x: 10, y: 10 }
          },
          {
            type: 'TextButton',
            name: 'ActionButton',
            text: 'Claim Reward',
            backgroundColor: '#a6e3a1',
            textColor: '#11111b',
            size: { x: 200, y: 50 },
            position: { x: 100, y: 220 }
          }
        ]
      }
    ]
  };

  const luauCode = `-- Roblox Studio UI Generation Code
-- Theme: ${selectedTheme} | Description: ${prompt}

local Players = game:GetService("Players")
local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local screenGui = Instance.new("ScreenGui")
screenGui.Name = "AIGeneratedGUI"
screenGui.ResetOnSpawn = false
screenGui.Parent = playerGui

local mainFrame = Instance.new("Frame")
mainFrame.Name = "MainPanel"
mainFrame.Size = UDim2.new(0, 400, 0, 300)
mainFrame.Position = UDim2.new(0.5, -200, 0.5, -150)
mainFrame.BackgroundColor3 = Color3.fromHex("1e1e2e")
mainFrame.BorderSizePixel = 2
mainFrame.BorderColor3 = Color3.fromHex("89b4fa")
mainFrame.Parent = screenGui

local uiCorner = Instance.new("UICorner")
uiCorner.CornerRadius = UDim.new(0, 12)
uiCorner.Parent = mainFrame

local titleLabel = Instance.new("TextLabel")
titleLabel.Name = "TitleHeader"
titleLabel.Size = UDim2.new(1, -20, 0, 40)
titleLabel.Position = UDim2.new(0, 10, 0, 10)
titleLabel.Text = "${prompt}"
titleLabel.TextColor3 = Color3.fromHex("cdd6f4")
titleLabel.TextSize = 20
titleLabel.Font = Enum.Font.GothamBold
titleLabel.BackgroundTransparency = 1
titleLabel.Parent = mainFrame

local actionBtn = Instance.new("TextButton")
actionBtn.Name = "ActionButton"
actionBtn.Size = UDim2.new(0, 200, 0, 50)
actionBtn.Position = UDim2.new(0.5, -100, 1, -70)
actionBtn.Text = "Interact"
actionBtn.BackgroundColor3 = Color3.fromHex("a6e3a1")
actionBtn.TextColor3 = Color3.fromHex("11111b")
actionBtn.Font = Enum.Font.GothamBold
actionBtn.TextSize = 16
actionBtn.Parent = mainFrame

local btnCorner = Instance.new("UICorner")
btnCorner.CornerRadius = UDim.new(0, 8)
btnCorner.Parent = actionBtn
`;

  res.json({
    success: true,
    guiSpecs,
    luauCode
  });
});

// 4. Asset & Thumbnail Prompter (ForgeGUI inspired)
app.post('/api/generate-asset-prompt', (req, res) => {
  const { assetType, style, description } = req.body;
  if (!description) {
    return res.status(400).json({ error: 'Description is required' });
  }

  const type = assetType || 'Roblox Thumbnail';
  const assetStyle = style || 'Vibrant 3D Render';

  const optimizedPrompt = `High quality ${type}, ${assetStyle} style. ${description}, professional lighting, octave render, Unreal Engine 5 aesthetic, Roblox game asset art, highly detailed, 8k resolution`;
  const negativePrompt = `blurry, low quality, distorted geometry, grainy, bad composition, watermark`;

  res.json({
    success: true,
    assetType: type,
    style: assetStyle,
    optimizedPrompt,
    negativePrompt,
    recommendedAspectRatio: type.includes('Thumbnail') ? '16:9' : '1:1'
  });
});

// 5. Saved Projects Management
app.get('/api/projects', (req, res) => {
  res.json({ projects: savedProjects });
});

app.post('/api/projects', (req, res) => {
  const { name, type, content } = req.body;
  if (!name || !content) {
    return res.status(400).json({ error: 'Name and content are required' });
  }

  const newProject = {
    id: 'proj_' + Date.now(),
    name,
    type: type || 'Script',
    content,
    createdAt: new Date().toISOString()
  };

  savedProjects.push(newProject);
  res.status(201).json({ success: true, project: newProject });
});

// Start Server
if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`AI Game Studio running on http://localhost:${PORT}`);
  });
}

module.exports = app;
